[project]
name = "RunAndWalk"
version = "1.0.0"
authors = [{ name = "eeriegoesd" }]
description = """Makes running and walking work off a hold key and a toggle key.

For full information about this mod and to report bugs, please visit: https://eeriegoesd.com/gaming/mods/"""

[project.urls]
"Info and bug reports" = "https://eeriegoesd.com/gaming/mods/"

[tool.sdkmod]
name = "Run And Walk"
mod_type = "Standard"
supported_games = ["BL1", "BL1E"]
coop_support = "Unknown"
auto_enable = true
download = "https://github.com/EerieGoesD/borderlands-1-goty-mods/raw/refs/heads/main/RunAndWalk/RunAndWalk.sdkmod"
license = {name = "GPL-3.0-or-later", url = "https://www.gnu.org/licenses/gpl-3.0.en.html" }
