[project]
name = "Crash Debug"
version = "1.0.0"
authors = [{ name = "eeriegoesd" }]
description = """Keeps a running note of what every mod is doing so if the game crashes you can check the last mod that ran, allowing you to debug.

For full information about this mod and to report bugs, please visit: eeriegoesd.com"""

[tool.sdkmod]
name = "Crash Debug"
mod_type = "Standard"
supported_games = ["BL1", "BL1E"]
coop_support = "Unknown"
auto_enable = "True"
download = "https://github.com/EerieGoesD/borderlands-1-goty-mods/raw/refs/heads/main/CrashDebug/CrashDebug.sdkmod"
license = {name = "All rights reserved" }
