[project]
name = "Teleport"
version = "1.0.0"
authors = [{ name = "eeriegoesd" }]
description = """Takes you to any place you have already been to in this playthrough.

For full information about this mod and to report bugs, please visit: eeriegoesd.com/gaming/mods"""

[tool.sdkmod]
name = "Teleport"
mod_type = "Standard"
supported_games = ["BL1", "BL1E"]
coop_support = "Unknown"
auto_enable = "True"

download = "https://github.com/EerieGoesD/borderlands-1-goty-mods/raw/refs/heads/main/Teleport/Teleport.sdkmod"
license = {name = "All rights reserved" }
